### ISSUE TITLE
Raised exception

### ISSUE THREAD

**Issue by rycao18** [neuralinternet/compute-subnet#114]
0|MINER  | INFO:     3.138.134.210:40490 - "POST /PerfInfo HTTP/1.1" 500 Internal Server Error
0|MINER  | TRACE:    3.138.134.210:40490 - ASGI [4] Send {'type': 'http.response.body', 'body': '<21 bytes>'}
0|MINER  | TRACE:    3.138.134.210:40490 - ASGI [4] Raised exception
0|MINER  | ERROR:    Exception in ASGI application
0|MINER  | Traceback (most recent call last):
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
0|MINER  |     result = await app(  # type: ignore[func-returns-value]
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
0|MINER  |     return await self.app(scope, receive, send)
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
0|MINER  |     raise exc from None
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
0|MINER  |     await self.app(scope, inner_receive, inner_send)
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 290, in __call__
0|MINER  |     await super().__call__(scope, receive, send)
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
0|MINER  |     await self.middleware_stack(scope, receive, send)
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
0|MINER  |     raise exc
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
0|MINER  |     await self.app(scope, receive, _send)
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 106, in __call__
0|MINER  |     async with anyio.create_task_group() as task_group:
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
0|MINER  |     raise BaseExceptionGroup(
0|MINER  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
0|MINER  | TRACE:    3.138.134.210:40490 - HTTP connection lost

**Comment by sospcie** [comment]
I am having the same error. Can anyone check it please?

**Comment by rycao18** [comment]
Same IP and same execiption
```0|MINER  | TRACE:    3.138.134.210:37832 - ASGI [2] Raised exception
0|MINER  | ERROR:    Exception in ASGI application
0|MINER  | Traceback (most recent call last):
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
0|MINER  |     result = await app(  # type: ignore[func-returns-value]
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
0|MINER  |     return await self.app(scope, receive, send)
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
0|MINER  |     raise exc from None
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
0|MINER  |     await self.app(scope, inner_receive, inner_send)
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 290, in __call__
0|MINER  |     await super().__call__(scope, receive, send)
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
0|MINER  |     await self.middleware_stack(scope, receive, send)
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
0|MINER  |     raise exc
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
0|MINER  |     await self.app(scope, receive, _send)
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 106, in __call__
0|MINER  |     async with anyio.create_task_group() as task_group:
0|MINER  |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
0|MINER  |     raise BaseExceptionGroup(
0|MINER  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
0|MINER  | TRACE:    3.138.134.210:37832 - HTTP connection lost```
